#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	[System.Serializable()]
	public partial class Club : System.Runtime.Serialization.ISerializable
	{
		private int _clubID;
		public virtual int ClubID
		{
			get
			{
				return this._clubID;
			}
			set
			{
				this._clubID = value;
			}
		}
		
		private string _clubName;
		public virtual string ClubName
		{
			get
			{
				return this._clubName;
			}
			set
			{
				this._clubName = value;
			}
		}
		
		private IList<Program> _programs = new List<Program>();
		public virtual IList<Program> Programs
		{
			get
			{
				return this._programs;
			}
		}
		
		#region ISerializable Implementation
		
		public Club()
		{
		}
		
		protected Club(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.ClubID = info.GetInt32("ClubID");
			this.ClubName = info.GetString("ClubName");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("ClubID", this.ClubID, typeof(int));
			info.AddValue("ClubName", this.ClubName, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
