#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class Club
	{
		private int _clubID;
		public virtual int ClubID
		{
			get
			{
				return this._clubID;
			}
			set
			{
				this._clubID = value;
			}
		}
		
		private string _clubName;
		public virtual string ClubName
		{
			get
			{
				return this._clubName;
			}
			set
			{
				this._clubName = value;
			}
		}
		
		private IList<Program> _programs = new List<Program>();
		public virtual IList<Program> Programs
		{
			get
			{
				return this._programs;
			}
		}
		
	}
}
#pragma warning restore 1591
