#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class PlayerPass
	{
		private int _playerPassID;
		public virtual int PlayerPassID
		{
			get
			{
				return this._playerPassID;
			}
			set
			{
				this._playerPassID = value;
			}
		}
		
		private byte[] _photo;
		public virtual byte[] Photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				this._photo = value;
			}
		}
		
		private string _passNumber;
		public virtual string PassNumber
		{
			get
			{
				return this._passNumber;
			}
			set
			{
				this._passNumber = value;
			}
		}
		
		private DateTime _expires;
		public virtual DateTime Expires
		{
			get
			{
				return this._expires;
			}
			set
			{
				this._expires = value;
			}
		}
		
		private int _playerID;
		public virtual int PlayerID
		{
			get
			{
				return this._playerID;
			}
			set
			{
				this._playerID = value;
			}
		}
		
		private Player _player;
		public virtual Player Player
		{
			get
			{
				return this._player;
			}
			set
			{
				this._player = value;
			}
		}
		
		private IList<TeamPlayer> _teamPlayers = new List<TeamPlayer>();
		public virtual IList<TeamPlayer> TeamPlayers
		{
			get
			{
				return this._teamPlayers;
			}
		}
		
	}
}
#pragma warning restore 1591
