#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class Player
	{
		private int _playerID;
		public virtual int PlayerID
		{
			get
			{
				return this._playerID;
			}
			set
			{
				this._playerID = value;
			}
		}
		
		private DateTime _dateOfBirth;
		public virtual DateTime DateOfBirth
		{
			get
			{
				return this._dateOfBirth;
			}
			set
			{
				this._dateOfBirth = value;
			}
		}
		
		private System.Nullable<System.Char> _mInitial;
		public virtual System.Nullable<System.Char> MInitial
		{
			get
			{
				return this._mInitial;
			}
			set
			{
				this._mInitial = value;
			}
		}
		
		private string _lName;
		public virtual string LName
		{
			get
			{
				return this._lName;
			}
			set
			{
				this._lName = value;
			}
		}
		
		private string _fName;
		public virtual string FName
		{
			get
			{
				return this._fName;
			}
			set
			{
				this._fName = value;
			}
		}
		
		private IList<Transaction> _transactions = new List<Transaction>();
		public virtual IList<Transaction> Transactions
		{
			get
			{
				return this._transactions;
			}
		}
		
		private IList<PlayerPass> _playerPasses = new List<PlayerPass>();
		public virtual IList<PlayerPass> PlayerPasses
		{
			get
			{
				return this._playerPasses;
			}
		}
		
	}
}
#pragma warning restore 1591
