#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class Player
	{
		private int _playerID;
		public virtual int PlayerID
		{
			get
			{
				return this._playerID;
			}
			set
			{
				this._playerID = value;
			}
		}
		
		private int? _teamID;
		public virtual int? TeamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				this._teamID = value;
			}
		}
		
		private string _playerPassID;
		public virtual string PlayerPassID
		{
			get
			{
				return this._playerPassID;
			}
			set
			{
				this._playerPassID = value;
			}
		}
		
		private byte[] _playerPhoto;
		public virtual byte[] PlayerPhoto
		{
			get
			{
				return this._playerPhoto;
			}
			set
			{
				this._playerPhoto = value;
			}
		}
		
		private DateTime _dateOfBirth;
		public virtual DateTime DateOfBirth
		{
			get
			{
				return this._dateOfBirth;
			}
			set
			{
				this._dateOfBirth = value;
			}
		}
		
		private Team _team;
		public virtual Team Team
		{
			get
			{
				return this._team;
			}
			set
			{
				this._team = value;
			}
		}
		
		private IList<Transaction> _transactions = new List<Transaction>();
		public virtual IList<Transaction> Transactions
		{
			get
			{
				return this._transactions;
			}
		}
		
	}
}
#pragma warning restore 1591
