#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	[System.Serializable()]
	public partial class Program : System.Runtime.Serialization.ISerializable
	{
		private int _programID;
		public virtual int ProgramID
		{
			get
			{
				return this._programID;
			}
			set
			{
				this._programID = value;
			}
		}
		
		private string _programName;
		public virtual string ProgramName
		{
			get
			{
				return this._programName;
			}
			set
			{
				this._programName = value;
			}
		}
		
		private int _clubID;
		public virtual int ClubID
		{
			get
			{
				return this._clubID;
			}
			set
			{
				this._clubID = value;
			}
		}
		
		private Club _club;
		public virtual Club Club
		{
			get
			{
				return this._club;
			}
			set
			{
				this._club = value;
			}
		}
		
		private IList<Team> _teams = new List<Team>();
		public virtual IList<Team> Teams
		{
			get
			{
				return this._teams;
			}
		}
		
		#region ISerializable Implementation
		
		public Program()
		{
		}
		
		protected Program(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.ProgramID = info.GetInt32("ProgramID");
			this.ProgramName = info.GetString("ProgramName");
			this.ClubID = info.GetInt32("ClubID");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("ProgramID", this.ProgramID, typeof(int));
			info.AddValue("ProgramName", this.ProgramName, typeof(string));
			info.AddValue("ClubID", this.ClubID, typeof(int));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
