#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class Role
	{
		private int _roleID;
		public virtual int RoleID
		{
			get
			{
				return this._roleID;
			}
			set
			{
				this._roleID = value;
			}
		}
		
		private string _roleName;
		public virtual string RoleName
		{
			get
			{
				return this._roleName;
			}
			set
			{
				this._roleName = value;
			}
		}
		
		private IList<ScopeAssignment> _scopeAssignments = new List<ScopeAssignment>();
		public virtual IList<ScopeAssignment> ScopeAssignments
		{
			get
			{
				return this._scopeAssignments;
			}
		}
		
		private IList<Permission> _permissions = new List<Permission>();
		public virtual IList<Permission> Permissions
		{
			get
			{
				return this._permissions;
			}
		}
		
	}
}
#pragma warning restore 1591
