//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackrModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeAssignment
    {
        public int ScopeAssignmentID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> PermissionID { get; set; }
        public int ScopeID { get; set; }
        public int ResourceID { get; set; }
        public bool IsDeny { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual Role Role { get; set; }
        public virtual WebUser WebUser { get; set; }
        public virtual Scope Scope { get; set; }
    }
}
