#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class Team
	{
		private int _teamID;
		public virtual int TeamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				this._teamID = value;
			}
		}
		
		private string _teamName;
		public virtual string TeamName
		{
			get
			{
				return this._teamName;
			}
			set
			{
				this._teamName = value;
			}
		}
		
		private int _programID;
		public virtual int ProgramID
		{
			get
			{
				return this._programID;
			}
			set
			{
				this._programID = value;
			}
		}
		
		private DateTime _startYear;
		public virtual DateTime StartYear
		{
			get
			{
				return this._startYear;
			}
			set
			{
				this._startYear = value;
			}
		}
		
		private DateTime _endYear;
		public virtual DateTime EndYear
		{
			get
			{
				return this._endYear;
			}
			set
			{
				this._endYear = value;
			}
		}
		
		private short _maxRosterSize;
		public virtual short MaxRosterSize
		{
			get
			{
				return this._maxRosterSize;
			}
			set
			{
				this._maxRosterSize = value;
			}
		}
		
		private short _minRosterSize;
		public virtual short MinRosterSize
		{
			get
			{
				return this._minRosterSize;
			}
			set
			{
				this._minRosterSize = value;
			}
		}
		
		private Program _program;
		public virtual Program Program
		{
			get
			{
				return this._program;
			}
			set
			{
				this._program = value;
			}
		}
		
		private IList<Player> _players = new List<Player>();
		public virtual IList<Player> Players
		{
			get
			{
				return this._players;
			}
		}
		
	}
}
#pragma warning restore 1591
