#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class TeamPlayer
	{
		private int _teamPlayerID;
		public virtual int TeamPlayerID
		{
			get
			{
				return this._teamPlayerID;
			}
			set
			{
				this._teamPlayerID = value;
			}
		}
		
		private int _teamID;
		public virtual int TeamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				this._teamID = value;
			}
		}
		
		private int _playerPassID;
		public virtual int PlayerPassID
		{
			get
			{
				return this._playerPassID;
			}
			set
			{
				this._playerPassID = value;
			}
		}
		
		private bool _isSecondary;
		public virtual bool IsSecondary
		{
			get
			{
				return this._isSecondary;
			}
			set
			{
				this._isSecondary = value;
			}
		}
		
		private Team _team;
		public virtual Team Team
		{
			get
			{
				return this._team;
			}
			set
			{
				this._team = value;
			}
		}
		
		private PlayerPass _playerPass;
		public virtual PlayerPass PlayerPass
		{
			get
			{
				return this._playerPass;
			}
			set
			{
				this._playerPass = value;
			}
		}
		
	}
}
#pragma warning restore 1591
