// Code is generated by Telerik Data Access Service Wizard
// using WebApiRepositories.tt template

using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Telerik.OpenAccess;
using TrackrModels;

namespace Trackr
{
	public partial class ClubRepository : OpenAccessBaseRepository<TrackrModels.Club, TrackrModels.ClubManagement>
    {
	
    }

    public partial class PlayerPassRepository : OpenAccessBaseRepository<TrackrModels.PlayerPass, TrackrModels.ClubManagement>
    {

    }

	public partial class PlayerRepository : OpenAccessBaseRepository<TrackrModels.Player, TrackrModels.ClubManagement>
    {
	
    }

	public partial class ProgramRepository : OpenAccessBaseRepository<TrackrModels.Program, TrackrModels.ClubManagement>
    {
	
    }

    public partial class TeamPlayerRepository : OpenAccessBaseRepository<TrackrModels.TeamPlayer, TrackrModels.ClubManagement>
    {

    }

	public partial class TeamRepository : OpenAccessBaseRepository<TrackrModels.Team, TrackrModels.ClubManagement>
    {
	
    }

	public partial class TransactionRepository : OpenAccessBaseRepository<TrackrModels.Transaction, TrackrModels.ClubManagement>
    {
	
    }

	public partial class TransactionTypeRepository : OpenAccessBaseRepository<TrackrModels.TransactionType, TrackrModels.ClubManagement>
    {
	
    }

	public partial class WebUserInfoRepository : OpenAccessBaseRepository<TrackrModels.WebUserInfo, TrackrModels.ClubManagement>
    {
	
    }

}
